Convert feed from and to Feed instance
Nonlinear-EA/The-Nonlinear-Library pull request #13
Opened 2023-03-23 10:13 UTC by aarangop

2023-03-24 00:25 UTC, maximumpeaches commented
I don't understand the purpose of the Feed and FeedEntry classes. I get that they wrap around feedparserdict. What if we use feedparserdict directly? The code would be simpler, because it'd be one less layer. In other words we could get rid of the Feed and FeedEntry class, which would reduce the code and the code complexity.   
  
I guess one argument to put a layer between feedparser and the rest of the code is in case we want to change feedparser in the future. So Feed and FeedEntry serve as an interface in a way. But I think the project is small enough, and we'd have to rewrite whatever code is using feedparser anyways if we decide to move away from it... so I'm not sure the extra complexity is worth it. What do you think?

2023-03-24 09:02 UTC, aarangop commented
Yes I think you're right. For now we can work directly on the feed parser, I've changed that with the latest commits.

2023-03-24 16:15 UTC, maximumpeaches commented on functions/feed.py
> +    # TODO: Check python version on the cloud since this syntax works for python >= 3.10
I'm selecting Python 3.11 when I deploy our Functions.

2023-03-24 17:29 UTC, maximumpeaches requested changes

2023-03-24 17:29 UTC, maximumpeaches commented on functions/podcast_feed_generator.py
> +                       max([SequenceMatcher(None, e['title'], h).ratio() for h in history_titles]) > 0.9]
Google Python Style Guide says not to use a nested for clause, here: https://google.github.io/styleguide/pyguide.html#27-comprehensions--generator-expressions Maybe good to just break out the inner for clause into a separate local variable. What do you think?

2023-03-24 17:29 UTC, maximumpeaches commented on functions/podcast_feed_generator.py
> +    feed['entries'] = [e for e in feed['entries'] if
What do you think about not using abbreviations? So `e` could be `entry`, or above `l` could be `line` or below `h` could be `history_title`. This is what's recommended in Google Python Style Guide here https://google.github.io/styleguide/pyguide.html#316-naming Looks like they allow iterators, but in general aren't crazy about them. I am flexible on this if you have a strong preference.

2023-03-24 17:29 UTC, maximumpeaches commented on functions/feed.py
> +    def get_search_period_timedelta(self) -> timedelta | None:
I like that you're using timedelta here. It seems like a better fit than the way the old code calculated time difference.

I think the regex here is overkill. If we want a timedelta of seven days, we could use an enum. For instance the code could something like this (might not be proper python style for the enum names, but you get the gist):
```python3
if self.search_period == 7_DAYS:
  return timedelta(days=7)
elif self.search_period == 1_DAY:
  return timedelta(days=1)
```

2023-03-24 18:15 UTC, maximumpeaches commented
@aarangop I'm not sure how obvious it is from the UI, but I added a commit in this pull request. Just wanted to let you know.

2023-03-25 14:36 UTC, aarangop commented on functions/podcast_feed_generator.py
> +def get_post_karma(url) -> str | None:
You're right, if the post cannot be accessed an exception is raised, otherwise a string is returned. Removed None from typehint.

2023-03-25 14:40 UTC, aarangop commented on functions/podcast_feed_generator.py
> +        feed['entries'] = list(filter(lambda s: regex.match(s['title']), feed['entries']))
I thought of the regex solution because it could be placed in an external file if we later decided to store that kind of parameters in static files and provides a lot of flexibility in terms of filtering. But I guess the titles will more or less stay the same so we can stick to the `startswith(title)`.

2023-03-25 14:50 UTC, aarangop commented on functions/podcast_feed_generator.py
> +    oldest_post_time = datetime.now(tz=timezone(timedelta(0))).replace(hour=0, minute=0, second=0,
If the posts have useful timezone information, we should include it, if they're always UTC it isn't necessary. From what I've seen so far they're always UTC, so I reverted it to `datetime.now()`.

2023-03-25 14:51 UTC, aarangop commented on functions/podcast_feed_generator.py
> +                       max([SequenceMatcher(None, e['title'], h).ratio() for h in history_titles]) > 0.9]
That's really good info, thanks, I implemented that and will have the guides in mind from now on, I haven't used them so far.

2023-03-25 14:53 UTC, aarangop commented on functions/feed.py
> +    def get_search_period_timedelta(self) -> timedelta | None:
Here I was also thinking about storing configuration data outside the code, so thought the regex version offered good flexibility and readability on the configuration file. If we're going to stick to daily and weekly though, I agree it's overkill. I implemented the enum solution. Let me know what you think

2023-03-25 14:54 UTC, aarangop commented
Yep, I pulled the new commit before  making the changes. What do you think? should we close this merge request and start a new one once the function returns an actual xml string? I'm kinda working towards that.

2023-03-25 14:58 UTC, aarangop commented on functions/podcast_feed_generator.py
> +    feed['entries'] = [e for e in feed['entries'] if
Agree, it's just habit, will try to stick to not using abbreviations.

2023-03-25 16:02 UTC, maximumpeaches approved these changes

2023-03-25 16:16 UTC, maximumpeaches commented
I think we'll want to look 24 hours or 7 days back from whenever the
Function is run. `datetime.now()` should pick up the timezone of whatever
server the Function is run on. So either we can just put the servers in
whatever time zone the RSS feeds use, or we can convert the RSS feeds to
the time zone of whatever machine they're working on. The former will
prevent us from moving our servers around but it might be easier when
running manual tests because you can just use that time zone in your tests
and you don't run into issues with timezone conversion between your machine
and the ones in GCP.

Anyways, this is out of scope for this pull request. Something we can work
on in the future.

On Sat, Mar 25, 2023 at 9:50 AM Andres Arango ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In functions/podcast_feed_generator.py
> <https://github.com/Nonlinear-EA/The-Nonlinear-Library/pull/13#discussion_r1148386266>
> :
>
> > +    feed['entries'] = [e for e in feed['entries'] if e['author'] not in removed_authors]
> +    print(f'{n_entries - len(feed["entries"])} removed because of removed authors...')
> +    n_entries = len(feed['entries'])
> +
> +    # Filter entries by forum using the provided title regex
> +    if feedconfig.title_regex:
> +        regex = re.compile(feedconfig.title_regex)
> +        feed['entries'] = list(filter(lambda s: regex.match(s['title']), feed['entries']))
> +        print(f'{n_entries - len(feed["entries"])} removed because of title mismatch...')
> +        n_entries = len(feed['entries'])
> +
> +    # Filter posts based on the requested search period
> +    # Get search period as timedelta
> +    search_period = feedconfig.get_search_period_timedelta()
> +    # Define the time of the oldest post that should come through
> +    oldest_post_time = datetime.now(tz=timezone(timedelta(0))).replace(hour=0, minute=0, second=0,
>
> If the posts have useful timezone information, we should include it, if
> they're always UTC it isn't necessary. From what I've seen so far they're
> always UTC, so I reverted it to datetime.now().
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Nonlinear-EA/The-Nonlinear-Library/pull/13#discussion_r1148386266>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACTL3AVQT65AFDZY2BNIPNLW54A35ANCNFSM6AAAAAAWE7IESY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-25 16:17 UTC, maximumpeaches approved these changes

2023-03-25 16:17 UTC, merged