Working unit tests
Nonlinear-EA/The-Nonlinear-Library pull request #37
Opened 2023-05-03 16:09 UTC by aarangop

I wrote a few unit tests to check that the function `update_beyondwords_feed` works correctly.

2023-05-04 02:58 UTC, maximumpeaches commented
Maybe we can rename update_podcast_feed function since it isn't super clear? What about create_feeds_from_beyondwords or something - I'm open to whatever you think is best.

2023-05-04 04:16 UTC, maximumpeaches commented
Overall very solid improvement and tests. I left some comments on things that could be improved. Good work on this!

2023-05-04 04:16 UTC, maximumpeaches requested changes

2023-05-04 04:16 UTC, maximumpeaches commented on test/files/test_forum_feed.xml
> +<?xml version="1.0" encoding="UTF-8"?>
So overall this file makes a lot of sense where you have the Lorem ipsum and the comments that say what the item is. That's great, and in general you have solid comments in your code that help a lot with comprehension, something not every developer does.

I think the normal convention is for each test to create test data which is particular to that test. So for instance you have one test that checks that posts with fewer than 250 words are discarded. That test could create a file which has an entry shorter than 250 words, and then check that it's removed, instead of sharing a XML file with other tests. There are two reasons for this. One is that then it's very easy for the person reading the test to understand why the test acts as it does. They just look at the file being created, which is created *in the test*, so it's all very obvious. The other advantage is that if you need to change the XML file then you will only impact that test. In general you want your tests to be independent (or orthogonal, to use a fancy word) to each other. Independence is not a hard and fast rule but if you think of a future developer who has to come and add a new test, are they going to want to understand an XML file that is used by a bunch of other tests? In general, no, they're just going to want to worry about their one particular test. Same goes for a developer who is fixing a bug in a test. Having just one test to fix is a lot easier than fixing something which impacts all the tests, because you only need to understand that one test.

As for how you create this test XML, I'm not sure. One option is to use the code you used in the production code which reads from a tree and writes from a tree. I love that code in production, but in tests we want to be as dumb as possible, and a dumber approach would be to just hardcode the XML in strings. But then if you have ten XML strings, one for each file, maybe that's actually more complicated, and if you need to update something about them then you need to update all ten of them. So I'm sort of torn. Normally I'd say just hardcode the XML in strings, like you've done here, because of [the DAMP principle](https://testing.googleblog.com/2019/12/testing-on-toilet-tests-too-dry-make.html) but either approach could make sense here. If you use the code which reads from a tree then it may be easier for you to set default values in the tests. For instance for the test which you write which checks whether the item with less than 250 words is removed, you could use a default value for the `<link>` tag, since it's irrelevant to the test. Whereas if you hardcoded the XML string then you'd need to include the `<link>` tag, even though it has nothing to do with the test. So probably overall makes more sense to just use the code which reads from a tree rather than the XML in strings in the tests?

2023-05-04 17:32 UTC, aarangop commented on feed_processing/feed_updaters.py
> +    # Remove items that might already be present in the feed.
nope, it'll be gone before we merge this.

2023-05-04 17:34 UTC, aarangop commented on test/conftest.py
> +    feed_root = etree.Element("rss", nsmap=feed_namespace_map)
It might be used again somewhere else but since it's not the case yet I've inlined it.

2023-05-04 17:36 UTC, aarangop commented on test/conftest.py
> +    Write the beyondwords feed to an initial state with only one item.
Okay cool, will keep this kind of thing in mind later on for other stuff.

2023-05-04 17:47 UTC, aarangop commented on test/conftest.py
> +def default_beyondwords_input_config():
I think for unit tests it's generally better to have fixtures instead of an global variable. Fixtures are generated anew for each test, so we don't have to worry about changed values and tests are more independent.

But maybe you didn't refer to that but only the location of the fixture. If that's the case, then yeah, I'll move it to the file that uses it, it makes sense since it declutters the conftest file. For reference pytest accesses the methods and variables inside the conftest file so it's a good place to have stuff that might be used across multiple test files.

2023-05-04 17:47 UTC, aarangop commented on test/test_update_podcast_feed.py
> +    history_titles = storage.read_history_titles()
This test is now gone since we don't use history_titles anymore. I worked on the old tests after I created the pull request. Sorry, I should've specified this in the pull request's comment. 

The new commits have the new versions of the old tests, which I think also have some improvements.

2023-05-04 18:13 UTC, aarangop commented
> Maybe we can rename update_podcast_feed function since it isn't super clear? What about create_feeds_from_beyondwords or something - I'm open to whatever you think is best.

Agree, will do. I was thinking though that we should have some sort of 'standard' terminology. There are various feeds at various stages so it should be clear what's what. In that spirit I created a flowchart where we could have the terminology as part of the documentation, you can see it on the readme. 

I'd suggest calling the function `create_feed_for_podcast_apps`

2023-05-05 01:58 UTC, maximumpeaches commented on test/conftest.py
> +def default_beyondwords_input_config():
Ok I didn't know that about conftest thanks.

2023-05-05 02:02 UTC, maximumpeaches commented
> > Maybe we can rename update_podcast_feed function since it isn't super clear? What about create_feeds_from_beyondwords or something - I'm open to whatever you think is best.
> 
> Agree, will do. I was thinking though that we should have some sort of 'standard' terminology. There are various feeds at various stages so it should be clear what's what. In that spirit I created a flowchart where we could have the terminology as part of the documentation, you can see it on the readme. 
> 
> I'd suggest calling the function `create_feed_for_podcast_apps`
> 
> Edit: maybe better `create_podcast_apps_feed`. I've implemented the suggestion above but maybe this is better and would update it in a future commit.
> 
> 

Yeah I think of them as "podcast providers" but the name doesn't have to be perfect. It's an improvement.

2023-05-05 02:07 UTC, maximumpeaches commented on test/files/test_forum_feed.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Yeah the suggested best practice I've been reading is like you're saying. Have some default values set up and then override them if they're specific to the test. Like if a test is checking entries have fewer than 250 words are removed, then it would set an item which has fewer than 250 words. See https://testing.googleblog.com/2018/02/testing-on-toilet-cleanly-create-test.html?m=1

2023-05-05 02:08 UTC, maximumpeaches commented on test/files/test_forum_feed.xml
> +<?xml version="1.0" encoding="UTF-8"?>
It seems generally fine for the tests to share a default value.

2023-05-05 02:09 UTC, maximumpeaches commented on test/conftest.py
> +def default_beyondwords_input_config():
Yeah my point was mostly about it being in the file. Usually if stuff is used by one file only then it makes sense to keep it in that file. Or same if it's used by one class only. But I didn't know that about conftest.

2023-05-05 02:12 UTC, maximumpeaches commented on test/test_beyondwords_feed_updater.py
> +def test_posts_with_no_paragraph_elements_in_content_are_discarded(
@aarangop Is this comment resolved by your updated tests? I can't tell on my phone.

2023-05-05 03:08 UTC, maximumpeaches commented
Hey I didn't take time to look at the updated tests. Let me know if doing so would be helpful though.

Main feedback I have is to just check that the titles exist in the results, applying that article I linked called Don't Put Logic In Tests, and to set relevant values in tests, applying that article I linked called Cleanly Create Test Data. After that feel free to merge or reach out to me if you want me to make another pass. (I'm on mobile and don't know how to approve the PR from here.)

2023-05-05 14:26 UTC, aarangop commented on test/test_beyondwords_feed_updater.py
> +def test_posts_that_area_already_present_in_other_relevant_files_are_discarded(
Solved!

2023-05-05 15:42 UTC, maximumpeaches commented on test/files/test_forum_feed.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This seems relevant: https://testing.googleblog.com/2017/01/testing-on-toilet-keep-cause-and-effect.html

2023-05-05 20:15 UTC, aarangop commented
> Hey I didn't take time to look at the updated tests. Let me know if doing so would be helpful though.
> 
> Main feedback I have is to just check that the titles exist in the results, applying that article I linked called Don't Put Logic In Tests, and to set relevant values in tests, applying that article I linked called Cleanly Create Test Data. After that feel free to merge or reach out to me if you want me to make another pass. (I'm on mobile and don't know how to approve the PR from here.)

In general I tried to stick to the principles from tott. The tests got a little bit longer but they're way more explicit now as to what they're doing. I got rid of a lot of fixtures and most things happen inside the tests. I mocked the `get_feed_tree_from_url` in each test so it returns explicitly the feed that is modified in the test. That way, there's no need for a bunch of different fixtures that provide different files.

2023-05-05 20:24 UTC, merged